/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2018-11-23 05:08:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mobile.scm.main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html> \n");
      out.write("<html> \n");
      out.write("<head> \n");
      out.write("\t<title>로그인</title> \n");
      out.write("\t<meta  name = \"viewport\" content = \"initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no\"><!-- // meta tag -->\n");
      out.write("\t<script src=\"http://code.jquery.com/jquery-1.11.1.min.js\"></script>\n");
      out.write("\t<link rel=\"stylesheet\" href=\"/component/dxTouch/codebase/touchui.css\" type=\"text/css\"> <!-- // dhtmlx touch file -->\t\n");
      out.write("\t<script src=\"/component/dxTouch/codebase/touchui.js\" type=\"text/javascript\"></script>  <!-- // dhtmlx touch file -->\n");
      out.write("\t\n");
      out.write("</head> \n");
      out.write("<body> \n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var w = $(window).width(); \n");
      out.write("var width = parseInt(w*0.6);\n");
      out.write("\n");
      out.write("//전체적으로 보았을 때, 400이상 넘었을 경우, 찌그러짐 현상 보이므로 400초과는 무조건 400으로 셋팅\n");
      out.write("if(width> 400) {\n");
      out.write("\twidth = 400;\n");
      out.write("}\n");
      out.write("\n");
      out.write("var form = {\n");
      out.write("\t    id: \"loginForm\",\n");
      out.write("\t    css: 'form',\n");
      out.write("\t    view: \"form\",\n");
      out.write("\t    height: 320,\n");
      out.write("\t    elements: [{\n");
      out.write("\t        view: \"imagebutton\",\n");
      out.write("// \t        template:\"<img src='/images/logo/m_is_big_logo.jpg' width='200' height='90' style='margin-top:5px; vertical-align:middle;'>\", //hegiht=90\n");
      out.write("\t        template:\"<img src='/images/logo/isdsLogo.png' id='imgBtn' width='\" + width + \"' height='100%' style='vertical-align:middle; margin:0;'>\", \n");
      out.write("\t        labelWidth:200,\n");
      out.write("\t        height:120,\n");
      out.write("\t        align:\"center\"\n");
      out.write("\t    },{\n");
      out.write("\t        view: \"text\",\n");
      out.write("\t        label: \"아이디\",\n");
      out.write("\t        name: \"login\",\n");
      out.write("\t        labelWidth: 90,\n");
      out.write("\t    }, {\n");
      out.write("\t        view: \"text\",\n");
      out.write("\t        type: \"password\",\n");
      out.write("\t        label: \"비밀번호\",\n");
      out.write("\t        name: \"password\",\n");
      out.write("\t        labelWidth: 90,\n");
      out.write("\t    }, {\n");
      out.write("\t        type: \"clean\",\n");
      out.write("\t        cols: [{\n");
      out.write("\t            view: \"button\",\n");
      out.write("\t            type: \"form\",\n");
      out.write("\t            label: \"로그인\",\n");
      out.write("\t            click: \"login();\"\n");
      out.write("\t        }]\n");
      out.write("\t    }]\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("var toolbar = {\n");
      out.write("    view: \"toolbar\",\n");
      out.write("    elements: [{\n");
      out.write("        view: \"label\",\n");
      out.write("        label: \"IS 동서 SCM - LOGIN\",\n");
      out.write("        align: \"center\"\n");
      out.write("    }]\n");
      out.write("};\n");
      out.write("var loginView = {\n");
      out.write("    type: \"clean\",\n");
      out.write("    css: \"layout\",\n");
      out.write("    rows: [toolbar, {gravity: 1}, {cols: [form]}, {gravity: 1}]\n");
      out.write("};\n");
      out.write("\n");
      out.write("dhx.ready(function() {\n");
      out.write("\tdhx.ui.fullScreen();\n");
      out.write("    dhx.ui(loginView);\n");
      out.write("});\n");
      out.write("\n");
      out.write("function login() {\n");
      out.write("    dhx.notice({\n");
      out.write("        delay: 750,\n");
      out.write("        message: \"Checking ...\"\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var formData = $$('loginForm').getValues();\n");
      out.write("    var uid = formData.login,\n");
      out.write("    \tpasswd = formData.password;\n");
      out.write("   \n");
      out.write("    if ( uid == '' ){\n");
      out.write("    \tdhx.alert(fn_alert('아이디를 입력하세요.'));\n");
      out.write("    }else if ( passwd == '' ){\n");
      out.write("    \tdhx.alert(fn_alert('패스워드를 입력하세요.'));\n");
      out.write("    }else{\n");
      out.write("    \t$('#id').val(uid)\n");
      out.write("    \t$('#pw').val(passwd)\n");
      out.write("    \t$.ajax({\n");
      out.write("        \turl:  \"/loginCheck\",\n");
      out.write("            type: \"POST\",\n");
      out.write("            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',\n");
      out.write("            data: $(\"#frm\").serialize(),\n");
      out.write("            dataType: \"json\",\n");
      out.write("            success: function(data) {\n");
      out.write("            \tif(data.id == null){\n");
      out.write("            \t\tdhx.alert(fn_alert(\"계정정보를 확인해주세요.\"));\n");
      out.write("            \t\treturn true;\n");
      out.write("            \t}else if(data.confirmYn == 0){\n");
      out.write("            \t\tdhx.alert(fn_alert(\"미승인 상태입니다..\"));\n");
      out.write("            \t\treturn true;\n");
      out.write("            \t}else{\n");
      out.write("            \t\tlocation.assign(\"/mobile/scm/main/main.do\");\n");
      out.write("            \t}\t\t\n");
      out.write("            },\n");
      out.write("            error: function(xhr) {\n");
      out.write("            \tdhx.alert(fn_alert(xhr+': error 발생'));\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<form id=\"frm\" name=\"frm\" method=\"post\">\n");
      out.write("<input type=\"hidden\" id=\"id\" name=\"id\" value=\"\">\n");
      out.write("<input type=\"hidden\" id=\"pw\" name=\"pw\" value=\"\">\n");
      out.write("</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
