/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2018-11-23 05:08:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.erp.scm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var mainLayout;\n");
      out.write("var mainTabbar;\n");
      out.write("var leftLayout;\n");
      out.write("var mainMenu;\n");
      out.write("var leftForm, leftToolbar;\n");
      out.write("var scrnParm;\n");
      out.write("var ActTabId;\n");
      out.write("var menuId;\n");
      out.write("$( document ).ready(function() {\n");
      out.write("\tmainLayout = new dhtmlXLayoutObject({//메인 layout 생성\n");
      out.write("\t\t\tparent: \"container\",\n");
      out.write("\t\t\tpattern: \"3T\"\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tmainLayout.forEachItem(function(cell){//cell 구분짓는 a,b,c remove\n");
      out.write("      cell.hideHeader();\n");
      out.write("\t});\n");
      out.write("\tmainLayout.cells(\"b\").showHeader();\n");
      out.write("\tmainLayout.cells(\"b\").setText(' ')\n");
      out.write("\tmainMenu = mainLayout.cells(\"b\").attachTree();\n");
      out.write("\tmainMenu.enableSmartCheckboxes(true);\n");
      out.write("\n");
      out.write("\tmainTabbar = mainLayout.cells(\"c\").attachTabbar();\n");
      out.write("\tmainLayout.cells(\"a\").attachObject(\"top\");\n");
      out.write("\tmainTabbar.enableAutoReSize(true);\n");
      out.write("\t\n");
      out.write("\tmainLayout.cells(\"b\").setWidth(240);\n");
      out.write("\tmainLayout.cells(\"a\").setHeight(30);\n");
      out.write("\tmainLayout.cells(\"a\").fixSize(false, true);\n");
      out.write("\n");
      out.write("\t/* 메뉴 쪽 레이아웃 사이즈 조절 가능*/\n");
      out.write("\tmainLayout.cells(\"b\").fixSize(true, false);\n");
      out.write("\tmainLayout.cells(\"b\").fixSize(false, true);\n");
      out.write("\n");
      out.write("\tmainTabbar.attachEvent(\"onSelect\", function(id, lastId){\n");
      out.write("\t\tmainMenu.getDxObj().selectItem(id); //Tabbar 클릭시 Tree scroll이 해당위치로 이동\n");
      out.write("\t\tmainMenu.getDxObj().focusItem(id); //Tabbar 클릭시 menu path get\n");
      out.write("\t\tgetViewFullPath(id); //왼쪽 상단의 페이지 풀 경로\n");
      out.write("\t\treturn true;\n");
      out.write("\t});\n");
      out.write("\t$(window).resize(function(){\n");
      out.write("\t\tmainLayout.setSizes();\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("\t$('#log_out').click(function(event) { //logout 버튼 클릭시\n");
      out.write("\t\tevent.preventDefault();\n");
      out.write("\t\tdhtmlx.confirm({\n");
      out.write("\t\t\ttitle:\"확 인\",\n");
      out.write("\t\t\tok:\"네\", cancel:\"아니오\",\n");
      out.write("\t\t\ttext:\"정말로 로그아웃 하시겠습니까?\",\n");
      out.write("\t\t\tcallback:function(result){\n");
      out.write("\t\t\t\tif(result)\n");
      out.write("\t\t\t\t\textLogout();\n");
      out.write("\t\t\t\telse\n");
      out.write("\t\t\t\t\treturn true;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\tfunction extLogout(){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : \"/logout\",\n");
      out.write("\t\t        type : \"POST\",\n");
      out.write("\t\t        dataType: \"json\"\n");
      out.write("\t\t\t});\n");
      out.write("\t\t\tlocation.replace(\"/erp/scm/login.do\");\n");
      out.write("\t\t}\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$('#home a').click(function(event) {//home 버튼 클릭 시 main으로 이동\n");
      out.write("\t\tevent.preventDefault();\n");
      out.write("\t\tlocation.replace(\"/erp/scm/main.do\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$('.dhxtabbar_tabs_ar_left').click(function(e) {//tabbar 좌화살표 클릭시 메뉴이동\n");
      out.write("\t\t mainTabbar.goToPrevTab();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$('.dhxtabbar_tabs_ar_right').click(function(e) {//tabbar 우화살표 클릭시 메뉴이동\n");
      out.write("\t\tmainTabbar.goToNextTab();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\tmenuTreeSearch();\n");
      out.write("});\n");
      out.write("function menuTreeSearch(){\n");
      out.write("\tvar obj = {};\n");
      out.write("\tobj.kind =\"web\";\n");
      out.write("\tgfn_callAjaxComm(obj,\"/erp/scm/menu\",load_treeCB,'');\n");
      out.write("}\n");
      out.write("\n");
      out.write("function load_treeCB(data){\n");
      out.write("\tif(mainMenu!=null) {\n");
      out.write("\t\tmainMenu.destructor();\n");
      out.write("\t}\n");
      out.write("\tmainMenu = mainLayout.cells(\"b\").attachTree();\n");
      out.write("\tmainMenu = new dxTree(mainMenu);\n");
      out.write("\tmainMenu.setData(data);\n");
      out.write("\tmainMenu.click(function(id){\n");
      out.write("\t\tfncSelectItem(mainMenu, id);\n");
      out.write("\t});\n");
      out.write("\tmainMenu.load(\"menucd\", \"pmenucd\", \"menuname\", mainMenu);\n");
      out.write("};\n");
      out.write("\n");
      out.write("var fncSelectItem = function(tree, id) {\n");
      out.write("\t\n");
      out.write("\tvar exegbn = \"\";\n");
      out.write("\ttry { // 폴더 클릭시 하위 목록 열고 닫는 로직\n");
      out.write("\t\texegbn = tree.getUserData(id, \"exegbn\");\n");
      out.write("\t\tif(exegbn==\"0\" && tree.getDxObj().getOpenState(id)==1) {\n");
      out.write("\t\t\ttree.getDxObj().closeItem(id);\n");
      out.write("\t\t} else {\n");
      out.write("\t\t\ttree.getDxObj().openItem(id);\n");
      out.write("\t\t\ttree.getDxObj().selectItem(id, false, false);\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t} catch(e){\n");
      out.write("\t\talert(e);\n");
      out.write("\t}\n");
      out.write("\tif(exegbn==\"1\") { // 윈도우 클릭시 실제 로드되는 로직\n");
      out.write("\t\tvar flag = true;\n");
      out.write("\t\tvar uri = tree.getUserData(id, \"uri\");\n");
      out.write("\t\tscrnParm = tree.getUserData(id, \"scrnParm\");\n");
      out.write("\t\t/*메뉴id 전역변수 처리*/\n");
      out.write("\t\tmenuId = id;\n");
      out.write("\t\n");
      out.write("\t\tvar menuItemText = tree.getDxObj().getItemText(id);\n");
      out.write("\t\tmainTabbar.forEachTab(function(tab){\n");
      out.write("\t\t    var tabId = tab.getId();\n");
      out.write("\t\t    if(id == tabId){ \n");
      out.write("\t\t\t\tflag=false;\n");
      out.write("\t\t\t\tmainTabbar.tabs(tabId).setActive();\n");
      out.write("\t\t\t\tmenuId = tabId;\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\tif(flag){\n");
      out.write("\t\t\tActTabId = id;\n");
      out.write("\t\t \t/*  closeBtn = '<input type=\"image\" src=\"/images/button/dhtmlx/close_2.gif\" width=\"11\" height=\"11\"'+\n");
      out.write("\t\t\t'id=\"closeBtn\" name=\"closeBtn\" onClick=\"closeEvent('+id+')\">';  */\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t//mainTabbar.addTab(id, menuItemText+'&nbsp;&nbsp;'+closeBtn, null, null, true, false);\n");
      out.write("\t\t\tmainTabbar.addTab(id, menuItemText, null, null, true, true);\n");
      out.write("            mainTabbar.tabs(id).attachURL(\"/\"+uri+\".do\");\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("};\n");
      out.write("\n");
      out.write("function getViewFullPath(id){\n");
      out.write("\tvar finalPath=\"\";\n");
      out.write("\tvar path;\n");
      out.write("\tvar level;\n");
      out.write("\tvar initPath = mainMenu.getDxObj().getItemText(id);\n");
      out.write("\n");
      out.write("\tlevel = mainMenu.getDxObj().getLevel(id);\n");
      out.write("\tmainMenu.getDxObj().selectItem(id);\n");
      out.write("\tdo {\n");
      out.write("\t\tvar parentId = mainMenu.getDxObj().getParentId(id);\n");
      out.write("\t\tpath = \" > \"+mainMenu.getDxObj().getItemText(parentId);\n");
      out.write("\t\tfinalPath = path+finalPath;\n");
      out.write("\t\tid = parentId;\n");
      out.write("\t\tlevel--;\n");
      out.write("\t}while (level > 1);\n");
      out.write("\t$(\"#pathbar\").val(finalPath.slice(2)+\" > \"+initPath);\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("<form id=\"hiddenform\" name=\"hiddenform\" method=\"post\">\n");
      out.write("    <input type=\"hidden\" id=\"scrnParm\" name=\"scrnParm\" />\n");
      out.write("</form>\n");
      out.write("<div id=\"top\">\n");
      out.write("    <div style=\"float:left;margin-top:3px;margin-left:20px;\" id=\"home\">\n");
      out.write("       <p class=\"crop\" id = \"home a\">\n");
      out.write("\t        <img id=\"\" alt=\"is_small_log\" src=\"/images/logo/is_small_logo.jpg\" width=\"100px;\" height=\"25px;\">\n");
      out.write("        </p>\n");
      out.write("\t  <span id='pathbar' style='font-weight:bold; border:0px;background-color:transparent;width:400px;'></span>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float:right;margin-top:5px;margin-right:20px;\" id=\"logout\">\n");
      out.write("         <input name='id' id='id' readonly style='width :120px; font-size:12px; font-weight:bold; margin-right:0px; border:0px;background-color:transparent; text-align:right' value=\"아이디 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("        <input name='userNm' id='userNm' readonly style='width :120px; font-size:12px; font-weight:bold; margin-right:20px; border:0px;background-color:transparent; text-align:right' value=\"이름 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("        <input name='custCd' id='custCd' readonly style='width :200px; font-size:12px; font-weight:bold; margin-right:50px; border:0px;background-color:transparent; text-align:right' value=\"거래처명 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${custNm}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\n");
      out.write("        <a href=\"#\" id=\"log_out\">로그아웃</a></div>\n");
      out.write("</div>\n");
      out.write("<div id=\"container\"></div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
