/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2019-04-18 08:20:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.mobile.scm.inusBath;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mItmShipR_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".dhx_loading_overlay{\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tbackground-color:#D6D6D6;\r\n");
      out.write("\topacity:0.5;\r\n");
      out.write("\tbackground-image:url(/component/dxTouch/codebase/imgs/loading.png);\r\n");
      out.write("\tbackground-repeat:no-repeat;\r\n");
      out.write("\tbackground-position:center;\r\n");
      out.write("};\r\n");
      out.write(".dhx_form{\r\n");
      out.write("background: #FFFFFF;\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var w = $(window).width(); \r\n");
      out.write("var h = $(window).height();\r\n");
      out.write("var h = h-175;\r\n");
      out.write("var date = dateformat(new Date());\r\n");
      out.write("var fullDate = new Date();\r\n");
      out.write("var hour = fullDate.getHours()+'';\r\n");
      out.write("var minute = fullDate.getMinutes();\r\n");
      out.write("if(minute <= 9){\r\n");
      out.write("\tminute = '0'+minute;\r\n");
      out.write("}\r\n");
      out.write("var form = { id: 'app', view: 'layout',\r\n");
      out.write("\t\trows: [\r\n");
      out.write("\t\t\t\t{ view: 'layout', type: 'wide',\r\n");
      out.write("\t\t\t\t\trows: [\r\n");
      out.write("\t\t\t\t\t\t{   type: \"clean\", height: 45,\r\n");
      out.write("\t\t\t\t\t        cols: [\r\n");
      out.write("\t\t\t\t\t          { view: \"button\", type: \"round\", label: \"메뉴목록\", click: \"fn_moveMain();\" }, \r\n");
      out.write("\t\t\t\t\t          { view: \"button\", type: \"round\", label: \"조회\", click: \"fn_search();\" }, \r\n");
      out.write("\t\t\t\t\t\t    ]\r\n");
      out.write("\t\t\t\t\t    },\r\n");
      out.write("\t\t\t\t\t\t{ view: 'form', scroll: false, height : 130,\r\n");
      out.write("\t\t\t\t\t\t\telements: [\r\n");
      out.write("\t\t\t\t\t\t\t\t{ view: 'text', label: '공사일자' , type:'date', id: 'frDt' , value:date},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ view: 'text', label: '&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;~' , type:'date', id: 'toDt' , value:date},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ view: \"combo\", label: '시공점', id: \"custCd\", select:true, datatype:'json', url:'/mobile/scm/inusBath/mSigongFinishR/combo'},\r\n");
      out.write("// \t\t\t\t\t\t\t\t{ view: \"text\", label: '시공점'  , id: \"custInfo\", readonly:true},\r\n");
      out.write("// \t\t\t\t\t\t\t\t{ view: \"text\", label: '시공점코드'\t, id: \"custCd\", readonly:true},\r\n");
      out.write("// \t\t\t\t\t\t\t\t{ view: \"text\", label: '시공점명' \t, id: \"custNm\", readonly:true},\r\n");
      out.write("\t\t\t\t\t\t\t], id: 'frmMain'\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t{ view: 'grid', datatype: 'json', id:'gridMain', select: true, scroll: \"xy\", height : h, \r\n");
      out.write("\t\t\t\t\t\t\tfields: [\r\n");
      out.write("\t\t\t\t\t\t\t\t{ width: 80, label: '시공여부'\t, template: function(obj) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar endChk = obj.endChk;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar endChkNm = obj.endChkNm == null ? \"\" : obj.endChkNm;\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar tag = endChkNm;\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\tif(\"SDH4110\"==endChk) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttag = \"<div style='background-color:#ffffc0;'>\"+ endChkNm + \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else if(\"SDH4120\"==endChk){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttag = \"<div style='background-color:#c0ffc0;'>\"+ endChkNm + \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t} else if(\"SDH4130\"==endChk){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttag = \"<div style='background-color:#c0c0ff;'>\"+ endChkNm + \"</div>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn tag;\r\n");
      out.write("\t\t\t\t\t\t\t\t} , type: 'custom', align: 'center', id:'endChkNm'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ width: 110, label: '고객명' , template: '#cusName#'  , type: 'custom', align: 'left'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ width: 80\t, label: '시공비매입' , template: function(obj){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar buyAmt = addComma(obj.buyAmt);\r\n");
      out.write("\t\t\t\t\t\t\t\t\treturn buyAmt;\r\n");
      out.write("\t\t\t\t\t\t\t\t}, type: 'custom', align: 'right'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ width: 400, label: '주소'\t\t, template: '#fldAddr#'\t, type: 'custom', align: 'left'},\r\n");
      out.write("\t\t\t\t\t\t\t\t{ width: 90, label: '견적번호'\t\t, template: '#estNo#'\t\t, type: 'custom', align: 'center'},\r\n");
      out.write("\t\t\t\t\t\t\t], header: true,\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t], id: 'sigongFinish'\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t]\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("var loginView = {\r\n");
      out.write("    type: \"clean\",\r\n");
      out.write("    css: \"layout\",\r\n");
      out.write("    rows: [toolbar, {gravity: 1}, { type: \"clean\", cols: [{ width: 15 }, form, {width: 15}]}, {gravity: 2}]\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("var search = \"\";\r\n");
      out.write("dhx.ready(function() {\r\n");
      out.write("\tdhx.ui.fullScreen();\r\n");
      out.write("    dhx.ui(form); \r\n");
      out.write("    \r\n");
      out.write("    search = window.location.search;\r\n");
      out.write("    if(search) {\r\n");
      out.write("    \tif(fn_setParam(search)) {\r\n");
      out.write("    \t\tfn_search();\r\n");
      out.write("    \t}\r\n");
      out.write("\t}\r\n");
      out.write("    \r\n");
      out.write("    //일자 시작일자는 해당 일의 1일로 설정\r\n");
      out.write("    var frDt = $$('frDt').getValue();\r\n");
      out.write("    $$('frDt').setValue(frDt.substring(0,8) + \"01\");\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    $$(\"gridMain\").attachEvent(\"onItemClick\",function(id,ev,trg){\r\n");
      out.write("    \tvar id = $('#gridId').val(id);\r\n");
      out.write("    \tvar rId = $('#gridId').val();\r\n");
      out.write("    \tvar list = $$('gridMain').item(rId);\r\n");
      out.write("\r\n");
      out.write("\t\tif(list.cusName == '') {\r\n");
      out.write("\t\t\treturn dhx.alert(fn_alert('선택된 고객이 없습니다.'));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar url = \"/mobile/scm/inusBath/mItmShipGrdDtlR.do?frDt=\" + $$('frDt').getValue() + \"?toDt=\" + $$('toDt').getValue() + \"?custCd=\" + $$('custCd').getValue() + \"?estNo=\" + list.estNo;\r\n");
      out.write("\t\tlocation.assign(url);\t//상세내역\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function fn_setParam(search) {\r\n");
      out.write("\tvar vb = true;\r\n");
      out.write("\tvar uri = decodeURI(search);\r\n");
      out.write("\t\r\n");
      out.write("\tif(uri != \"\" || uri != null || uri != undefined) {\r\n");
      out.write("\t\turi = uri.slice(1, uri.length);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar param = uri.split('?');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfor(var i=0; i < param.length; i++) {\r\n");
      out.write("\t\t\tvar devide = param[i].split('=');\r\n");
      out.write("\t\t\t$$(devide[0]).setValue(devide[1]);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvb = false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\treturn vb;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_moveMain() {\r\n");
      out.write("\tlocation.assign(\"/mobile/scm/main/main.do\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_search(){\r\n");
      out.write("\tvar obj = {};\r\n");
      out.write("\tobj.frDt = searchDate($$('frDt').getValue(),\"-\");\r\n");
      out.write("\tobj.toDt = searchDate($$('toDt').getValue(),\"-\");\r\n");
      out.write("\tobj.custCd = $$('custCd').getValue();\r\n");
      out.write("\t\r\n");
      out.write("\tif((obj.frDt == \"\" ||obj.frDt == null || obj.frDt == undefined) || (obj.toDt == \"\" || obj.toDt == null || obj.toDt == undefined)){\r\n");
      out.write("\t\tdhx.alert(fn_alert('공사일자를 입력하세요'));\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else if(obj.custCd == \"\" ||obj.custCd == null || obj.custCd == undefined){\r\n");
      out.write("\t\tdhx.alert(fn_alert('시공점코드는 필수입니다'));\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\tvar gridMain = $$('gridMain');\r\n");
      out.write("\t\tdhx.extend(gridMain, dhx.OverlayBox);\r\n");
      out.write("\t\tgridMain.showOverlay();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tmobileAjax(\"/mobile/scm/inusBath/mItmShipR/list\",obj,function(data){\r\n");
      out.write("\t\t\tsearch = \"\";\t//조회 후 초기화\r\n");
      out.write("\t\t\tgridMain.clearAll();\r\n");
      out.write("\t\t\tgridMain.define('datatype', 'json');\r\n");
      out.write("\t\t\tgridMain.define('data', data);\r\n");
      out.write("\t\t\tgridMain.adjust();\r\n");
      out.write("\t\t\tfn_searchCB(data);\r\n");
      out.write("\t\t\tgridMain.refresh();\r\n");
      out.write("\t\t\tgridMain.hideOverlay();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function fn_searchCB(data) {\r\n");
      out.write("\twindow.setTimeout(function() {\r\n");
      out.write("\t\t$$('custCd').refresh();\r\n");
      out.write("    }, 1000)\t//0.1초 [1초:1000]\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addComma(num) {\r\n");
      out.write("  var regexp = /\\B(?=(\\d{3})+(?!\\d))/g;\r\n");
      out.write("  return num.toString().replace(regexp, ',');\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("<form id=\"pForm\" name=\"pForm\">\r\n");
      out.write("<input type=\"hidden\" id=\"gridId\" name=\"gridId\">\r\n");
      out.write("</form>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
