/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.62
 * Generated at: 2020-03-04 04:53:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.site.ISDS.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class resGuid_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tld/html.tld", Long.valueOf(1541752441499L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t<!--\r\n");
      out.write("\r\n");
      out.write("\t\tfunction init(){\r\n");
      out.write("\t\t\tvar seq = $(\"#boardCateSeq\").val();\r\n");
      out.write("\t\t\tif(seq==\"\"){\r\n");
      out.write("\t\t\t\t$(\"#col1\").addClass(\"on\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\t$(\"#col\"+seq).addClass(\"on\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction noticeCate(code){\r\n");
      out.write("\t\t\t$(\"#page\").val(1);\r\n");
      out.write("\t\t\t$(\"#boardCateSeq\").val(code);\r\n");
      out.write("\t\t\tdocument.faqForm.action = \"bbt00004.do?pageCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardMstCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t\tdocument.faqForm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction noticeView(seq){\r\n");
      out.write("\t\t\t$(\"#boardSeq\").val(seq);\r\n");
      out.write("\t\t\tdocument.faqForm.action = \"bbt00004V.do?pageCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardMstCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t   \tdocument.faqForm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction doPage(pageNum){\r\n");
      out.write("\t\t\tdocument.faqForm.page.value = pageNum;\r\n");
      out.write("\t    \tdocument.faqForm.action = \"bbt00004.do?pageCd=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${boardMstCd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t       \tdocument.faqForm.submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//태그 문자열을 디코딩 한다\r\n");
      out.write("\t\tfunction decodeTag(str){\r\n");
      out.write("\t\t\treturn str && str.replace(/&quot;/g,\"\\\"\").replace(/&lt;/g,\"<\").replace(/&gt;/g,\">\").replace(/&nbsp;/g,\" \").replace(/&amp;/g,\"&\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t//-->\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \t<div class=\"sub\"> -->\r\n");
      out.write("<!-- \t\t<div class=\"box_guide\"> -->\r\n");
      out.write("<!-- \t\t\t<h2 class=\"tit\">서비스요금 안내</h2> -->\r\n");
      out.write("<!-- \t\t\t<div class=\"page_location\"> -->\r\n");
      out.write("<!-- \t\t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\"><span class=\"home\"><span class=\"hidden\">home</span></span></a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li><a href=\"#\">서비스예약</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t\t<li class=\"last\"><a href=\"#\">서비스요금 안내</a></li> -->\r\n");
      out.write("<!-- \t\t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t\t</div> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t\t<!--// box_guide -->\r\n");
      out.write("<!-- \t\t<div class=\"msg_bx fee\"> -->\r\n");
      out.write("<!-- \t\t\t<strong>서비스요금은 출장비 + 수리비 + 부품비의 합으로 청구됩니다.</strong> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\r\n");
      out.write("<!-- \t\t<div class=\"cont_bx\"> -->\r\n");
      out.write("<!-- \t\t\t<h3>품질보증기간</h3> -->\r\n");
      out.write("<!-- \t\t\t<ul> -->\r\n");
      out.write("<!-- \t\t\t\t<li>저희 이누스는 공정거래위원회에서 고시한 소비자분쟁해결기준을 준수 합니다.</li> -->\r\n");
      out.write("<!-- \t\t\t\t<li>제품의 품질보증기간은 제품의 인도(설치)날로부터 1년 이내의 기간을 말합니다. (판매조건에 따라 품질보증기간이 다를 수 있음)</li> -->\r\n");
      out.write("<!-- \t\t\t</ul> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t\t<!--// 품질보증기간 -->\r\n");
      out.write("<!-- \t\t<div class=\"cont_bx\"> -->\r\n");
      out.write("<!-- \t\t\t<h3>유/무상 수리의 기준</h3> -->\r\n");
      out.write("<!-- \t\t\t<dl> -->\r\n");
      out.write("<!-- \t\t\t\t<dt>무상수리</dt> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>제품의 품질보증기간내에 정상적인 사용 상태에서 발생한 품질, 성능 등의 고장인 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>A/S 수리 후 3개월 이내 동일 부위 재 고장인 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd class=\"bgx\">고장이 아닌 상태에서 출장서비스를 받으시는 경우 출장비용이 부과 되오니 자주하는질문 또는 간단조치를 잘 살펴보시길 바랍니다.</dd> -->\r\n");
      out.write("<!-- \t\t\t</dl> -->\r\n");
      out.write("<!-- \t\t\t<dl> -->\r\n");
      out.write("<!-- \t\t\t\t<dt>유상수리</dt> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>제품의 품질보증기간이 경과된 제품</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>외부 환경이나 충격으로 인한 손상 또는 고장이 발생된 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>사용설명서 내의 주의사항을 지키지 않아 고장이 발생한 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>당사의 지정 서비스센터가 아닌 다른 사람이 수리하여 고장이 발생한 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>당사의 지정 부품이 아닌 부품을 가공 또는 수리하여 고장이 발생한 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>소모성 부품의 수명이 다하여 고장이 발생한 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>제품의 최초 설치 장소에서 이전을 요청 하는 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>천재지변으로 인한(수해, 지진, 화재) 고장이 발생될 경우</dd> -->\r\n");
      out.write("<!-- \t\t\t</dl> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t\t<!--// 유/무상 수리의 기준 -->\r\n");
      out.write("<!-- \t\t<div class=\"cont_bx\"> -->\r\n");
      out.write("<!-- \t\t\t<h3>요금 산정 기준</h3> -->\r\n");
      out.write("<!-- \t\t\t<dl> -->\r\n");
      out.write("<!-- \t\t\t\t<dt>유상 출장비</dt> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>출장수리가 필요한 경우 11,000원 청구</dd> -->\r\n");
      out.write("<!-- \t\t\t</dl> -->\r\n");
      out.write("<!-- \t\t\t<dl> -->\r\n");
      out.write("<!-- \t\t\t\t<dt>수리비</dt> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>수리가 필요한 경우 11,000원 청구</dd> -->\r\n");
      out.write("<!-- \t\t\t</dl> -->\r\n");
      out.write("<!-- \t\t\t<dl> -->\r\n");
      out.write("<!-- \t\t\t\t<dt>부품비</dt> -->\r\n");
      out.write("<!-- \t\t\t\t<dd>수리에 필요한 부품 사용 시 부품비 청구</dd> -->\r\n");
      out.write("<!-- \t\t\t</dl> -->\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t\t<!--// 요금 산정 기준 -->\r\n");
      out.write("<!-- \t</div> -->\r\n");
      out.write("\t<!--// sub -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"sub\">\r\n");
      out.write("\t\t<div class=\"box_guide\">\r\n");
      out.write("\t\t\t<h2 class=\"tit\">서비스요금 안내</h2>\r\n");
      out.write("\t\t\t<div class=\"page_location\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><span class=\"home\"><span class=\"hidden\">home</span></span></a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">서비스예약</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"last\"><a href=\"#\">서비스요금 안내</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div style=\"height:30px;\">\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"cont_bx\">\r\n");
      out.write("\t\t\t<h3>제품별 서비스 기준</h3>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>당사는 기본적으로 출장서비스를 진행하고 있습니다.</li>\r\n");
      out.write("\t\t\t\t<li>단, 일부 품목은 택배수리로만 진행하고 있으니 자세한 문의는 고객센터 대표번호로 연락주시기 바랍니다.</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"cont_bx\">\r\n");
      out.write("\t\t\t<h3>품질보증기간</h3>\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li>저희 이누스는 공정거래위원회에서 고시한 소비자분쟁해결기준을 준수 합니다.</li>\r\n");
      out.write("\t\t\t\t<li>제품의 품질보증기간은 제품의 인도(설치)날로부터 1년 이내의 기간을 말합니다. (판매조건에 따라 품질보증기간이 다를 수 있음)</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"cont_bx\">\r\n");
      out.write("\t\t\t<h3>유/무상 수리의 기준</h3>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>무상수리</dt>\r\n");
      out.write("\t\t\t\t<dd>제품의 품질보증기간내에 정상적인 사용 상태에서 발생한 품질, 성능 등의 고장인 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>A/S 수리 후 3개월 이내 동일 부위 재 고장인 경우</dd>\r\n");
      out.write("\t\t\t\t<dd class=\"bgx\">고장이 아닌 상태에서 출장서비스를 받으시는 경우 출장비용이 부과 되오니 자주하는질문 또는 간단조치를 잘 살펴보시길 바랍니다.</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>유상수리</dt>\r\n");
      out.write("\t\t\t\t<dd>제품의 품질보증기간이 경과된 제품</dd>\r\n");
      out.write("\t\t\t\t<dd>외부 환경이나 충격으로 인한 손상 또는 고장이 발생된 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>사용설명서 내의 주의사항을 지키지 않아 고장이 발생한 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>당사의 지정 서비스센터가 아닌 다른 사람이 수리하여 고장이 발생한 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>당사의 지정 부품이 아닌 부품을 가공 또는 수리하여 고장이 발생한 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>소모성 부품의 수명이 다하여 고장이 발생한 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>제품의 최초 설치 장소에서 이전을 요청 하는 경우</dd>\r\n");
      out.write("\t\t\t\t<dd>천재지변으로 인한(수해, 지진, 화재) 고장이 발생될 경우</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"cont_bx\">\r\n");
      out.write("\t\t\t<h3>요금 산정 기준</h3>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>출장서비스</dt>\r\n");
      out.write("\t\t\t\t<dt>출장비+수리비+부품비의 합으로 청구됩니다.</dt>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<dd>출장비는 출장수리를 요구하는 경우 적용되며 지역별로 차등 청구됩니다.</dd>\r\n");
      out.write("\t\t\t\t<dd>수리비는 유료 수리 시 부품비를 제외한 기술료를 말합니다.</dd>\r\n");
      out.write("\t\t\t\t<dd>부품비는 수리 시 부품 교체를 할 경우 소요되는 부품가격을 말합니다.</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t\t<dl>\r\n");
      out.write("\t\t\t\t<dt>택배서비스</dt>\r\n");
      out.write("\t\t\t\t<dt>택배비+수리비+부품비의 합으로 청구됩니다.</dt>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<dd>택배비는 센터로 제품을 입고시켜 수리 후 다시 고객 지역까지 배달하는 비용입니다. (택배사 요금 기준에 준함)</dd>\r\n");
      out.write("\t\t\t\t<dd>수리비는 유료 수리 시 부품비를 제외한 기술료를 말합니다.</dd>\r\n");
      out.write("\t\t\t\t<dd>부품비는 수리 시 부품 교체를 할 경우 소요되는 부품가격을 말합니다.</dd>\r\n");
      out.write("\t\t\t\t<dd>운송 중 발생하는 파손 및 분실에 대해서는 제조사에서 보상하지 않습니다.</dd>\r\n");
      out.write("\t\t\t</dl>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!--// sub -->\r\n");
      out.write("\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
